### PR TITLE
Add chain plugin calls

### PR DESCRIPTION
**Pull request by red2678**
This is a must know for me. For a long time, I did not do this and my jQuery code most undoubtedly suffered. 

Let me know if I need to change anything.

### CODE REVIEW

**Comment by huei90** [comment]
:+1:

**Comment by AllThingsSmitty** [comment]
@red2678 the branch has some conflicts before it can be merged. Can you resolve those? Thanks.

**Comment by AllThingsSmitty** [comment]
@red2678 don't worry, I'll see about resolve those

**Comment by red2678** [comment]
@AllThingsSmitty I am at work right now, but can totally do it when I get home. Won't take long just need to merge master.

**Comment by AllThingsSmitty** [comment]
@red2678 sounds good.  Thanks.

**Comment by red2678** [comment]
Well I merged but it is still showing conflicts. Being somewhat new to Git, perhaps you could point me in the correct direction?

**Comment by AllThingsSmitty** [comment]
Let me take a look.

**Comment by AllThingsSmitty** [comment]
I think what happened is the changes you made weren't against the latest branch. That would've created merge conflicts with where you were inserting the changes. I wasn't able to resolve so I just pasted your changes directly in with commit https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/commit/12fb4be8d9c64ed39f4b0592b80906fc02aa4d37. Sorry about that.

**Comment by red2678** [comment]
No problem man! As long as it was added :+1:

**Pull request closed without merging**
