### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by Katamori**
Sadly internal links fail to work - if anyone has an idea, why, I'll fix them ASAP. Until that, I made a pull request.

Moreover, I removed the other translations on my branch to prevent any potential conflict, but if that's an issue, I'll re-add them in an additional commit.

### CODE REVIEW

**Comment by 102** [comment]
Removing all other translations, you're proposing to delete them from the repository, you shouldn't worry about potential conflicts, if you don't do any changes.

To make links work again, you have to update them. For example, the following link:
`1. [CSS osztály aktiválása a kurzor hatására](#checking-if-jquery-loaded)`
should be updated to
`1. [CSS osztály aktiválása a kurzor hatására](#betöltött-e-a-jquery---ellenőrzés)`

You can find these links on the left of titles when you hover them.

**Comment by Katamori** [comment]
Holy sh-...terribly sorry then.

Thanks for the info, gonna make a commit to address these issues.

**Comment by 102** [comment]
> Holy sh-...terribly sorry then.

You shouldn't be so sorry as well. You're trying to do something good for open-source and shouldn't be afraid to do something wrong. That's what PRs are required for.

**Comment by Katamori** [comment]
Done!

If anything else is missing, let me know; otherwise, feel free to merge.

**Comment by AllThingsSmitty** [comment]
Thanks!

**Pull request merged**
