### PR TITLE
Complete translate in ko-KR

### PR DESCRIPTION
**Pull request by danielsychoo**
Hi, I've completed translate in ko-KR.
and I've added translation link in README.md.
(path is -> https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/tree/master/translations/ko-KR)
so maybe if you merge, you will see right away.
I'm glad to translate this project. :D thank you!

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
It looks like some additional files that are related to this repo were included with your commit. Please remove anything under the "ideas" directory and only commit the master README.md and /translations/ko-KO/README.md. Additionally, please place the link to the Korean translation on the master README.md after the Magyar link.

**Comment by danielsychoo** [comment]
@AllThingsSmitty 
Maybe I think the '.idea' directory is because of 'Webstorm'.
I deleted '.idea' and another things.
and placed Korean link after the Magyar link.

If you need another thing more, please comment again. Thank you. :D

**Comment by AllThingsSmitty** [comment]
Thanks, but it looks like your latest commit contains changes delete other files in the repo. Please only commit the master README.md and /translations/ko-KO/README.md files.

**Comment by danielsychoo** [comment]
Sorry, maybe I didn't understand about "Please only commit the master README.md and /translations/ko-KO/README.md files." means

I restored master README.md and Added Korean link after the Magyar link.
is it right?

**Review by AllThingsSmitty — COMMENTED** [review]
@danielsychoo have you had a chance to review the comments I entered in the file changes?

**Comment by danielsychoo** [comment]
I am sorry for not checking that part. 

However, I found out that VSCode automatically caused an error you mentioned once I add a link on translated list. I already checked several times, so please refer to that.

At the moment, I found a way to add the certain part without an error by using Webstorm, so I made a commit so that only link for translation can be added.

**Pull request merged**
